[en]
    languageName = "English"
    contentDir = "content"
    weight = 1
    [en.params.head]
        tagline = "A versatile business theme"
    # [en.params.footer]
    #     license = "All rights reserved."
    [en.params.social]
        title = "Follow us"

[nl]
    languageName = "Nederlands"
    weight = 2
    [nl.params.head]
        tagline = "Een veelzijdig thema voor je organisatie"
    # [nl.params.footer]
    #     license = "Alle rechten voorbehouden."
    [nl.params.social]
        title = "Volg ons"
    [nl.permalinks]
        [nl.permalinks.page]
            services = '/diensten/:slug/'
            markets = '/markten/:slug/'
            insights = '/actueel/:slug/'
            support = '/hulp/:slug/'
            about = '/over-ons/:slug/'
            contacts = '/contactpersonen/:slug/'
        [nl.permalinks.section]
            services = '/diensten/'
            markets = '/markten/'
            insights = '/actueel/'
            support = '/hulp/'
            about = '/over-ons/'
            contacts = '/contactpersonen/'
