[main]
    separator = "-"
    description = "Hinode Business is a versatile business theme powered by Hugo and Bootstrap 5."
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = false
    footerBelowFold = true
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "libsass"

[modules]
    [modules.flexsearch]
        frontmatter = true
        filter = "content_blocks"
    [modules.bookshop.title]
        preheadingPlacement = "above"


[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = false

[docs]
    github = "https://github.com/gethinode/hinode"
    release = "https://github.com/gethinode/hinode/releases/tag/"
    checkVersion = false

[home]
    # sections = ["posts"]
    fullCover = true
    centerHeadline = false
    style = ""

[footer]
    logo = "/img/logo-mono-light.svg"
    mode = true

[navigation]
    anchor = true
    logo = "/img/logo_icon_purple.svg"
    color = "body"
    fixed = true
    offset = "5.5rem"
    overlay = true
    overlayMode = "dark"
    search = true
    searchModal = true
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[connect]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[connect.providers]]
    name = "LinkedIn"
    label = "LinkedIn"
    url = "{value}"
    icon = "fab linkedin"
    weight = 10

[[connect.providers]]
    name = "Email"
    label = "Email"
    url = "{value}"
    icon = "fa envelope"
    weight = 20
    form = true

# toml-docs-start sections
# [sections]
#     [sections.posts]
#         title = "Posts"
#         sort = "date"
#         reverse = true
#         nested = true
#         cols = 3
#         color = ""
#         padding = "0"
#         header = "full"
#         footer = "none"
#         orientation = "stacked"
#         style = "border-0 card-zoom"
#         homepage = 3
#         separator = true
# toml-docs-end sections

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Hind"
    themeFontPath = "/fonts" # local path
    themeFontPreload = "/fonts/hind-v16-latin-regular.woff2"
    fontSizeBase = "1.1rem"
    purge = true

[schema]
    type = "Organization"
    name = "Hinode"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    github = "https://github.com/gethinode/hinode"
    section = "blog"
    [author]
        name = "Mark Dumay"
        # twitter = "https://twitter.com/markdumay"
        linkedin = "https://www.linkedin.com/in/markdumay/"
        github = "https://github.com/markdumay"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[links]
    hinode = "https://gethinode.com"

# provide default hero settings
[modules.bookshop.hero]
  align = "start"
  backdrop = "/assets/img/nat-9l98kFByiao-unsplash.jpg"
  overlayMode = "dark"
  section = true
  default = ["page", "home", "section"]

[pages]
    [pages.blog]
        header = "full"
    [pages.cases]
        header = "full"
